apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.fullnameOverride }}
spec:
  type: ClusterIP
  ports:
    - name: service
      port: 8181
      targetPort: 8181
    - name: metrics
      port: 8182
      targetPort: 8182
  selector:
    app: {{ .Values.fullnameOverride }}
  sessionAffinity: None
